### ISSUE TITLE
Blade server crashed error after upgrading to 1.14.0

### ISSUE THREAD

**Issue by badalsurana** [onecentlin/laravel-blade-snippets-vscode#44]
i just updated the extension to v1.14.0 and I am getting below error in my vscode

> "The Blade Language Server server crashed 5 times in last 3 minutes. The server will not be restarted."

Error output

`Error: Cannot find module '/Users/badalsurana/.vscode/extensions/onecentlin.laravel-blade-1.14.0/server/out/htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (/Users/badalsurana/.vscode/extensions/onecentlin.laravel-blade-1.14.0/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)`

`[Error - 3:10:42 PM] Connection to server got closed. Server will not be restarted.`

**Comment by WitekS** [comment]
`module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\server\out\htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 11:48:41] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\server\out\htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 11:48:41] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\server\out\htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 11:48:42] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\server\out\htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 11:48:42] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\server\out\htmlServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\witoslaw.sosnowski\.vscode\extensions\onecentlin.laravel-blade-1.14.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Error - 11:48:42] Connection to server got closed. Server will not be restarted.`

**Comment by dan3460** [comment]
Installed and it seems to be working properly, but the output console is giving me the following error:
'''
[Error - 7:32:18 AM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'extensionsPath' of undefined
'''
I will continue to test.

**Comment by WitekS** [comment]
this is probably a mistake resulting from the setting for emmet
```
  // Path to a folder containing Emmet profiles and snippets.'
  "emmet.extensionsPath": null,
```

**Comment by badalsurana** [comment]
i am also getting the same error 

> [Error - 6:16:43 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'extensionsPath' of undefined

**Comment by dan3460** [comment]
Spoke too soon, getting several error similar to this one, going back to the other blade highlight extension in the mean time.:
[Error - 7:41:44 AM] Error while computing completions for file:///c%3A/Users/dkolb/Documents/Develop/DekaySoftware/FDR/fsmadmV2.0/resources/views/layouts/navFacility.blade.php: Cannot read property 'showExpandedAbbreviation' of undefined
TypeError: Cannot read property 'showExpandedAbbreviation' of undefined
    at doComplete (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\node_modules\vscode-emmet-helper\out\emmetHelper.js:44:20)
    at Object.onHtmlContent (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\node_modules\vscode-emmet-helper\out\emmetHelper.js:867:35)
    at C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\modes\htmlMode.js:35:37
    at Array.forEach (native)
    at Object.doComplete (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\modes\htmlMode.js:34:44)
    at Object.<anonymous> (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\htmlServerMain.js:311:43)
    at step (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\htmlServerMain.js:36:23)
    at Object.next (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\htmlServerMain.js:17:53)
    at fulfilled (C:\Users\dkolb\.vscode\extensions\onecentlin.laravel-blade-1.14.1\server\out\htmlServerMain.js:8:58)
    at <anonymous>

**Comment by Melchyore** [comment]
Same error as @dan3460

**Comment by V-ed** [comment]
I am experiencing the same problem after the update.

What I did though is take the first fix from @tiansin from [the issue with syntax problem, before the server feature was added](https://github.com/onecentlin/laravel-blade-snippets-vscode/issues/42#issuecomment-365710200) and install that instead.

This also meant that I had to disable automatic extension updating in the meantime, as the `1.14.1` update kept installing itself. This could be done adding the setting `"extensions.autoUpdate": false,` in your user settings.

I find this to be the best solution while waiting for the server addon (_well, where autocompletion of css and scripts can be acheived_) to be fixed.
